// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAViOuuNWrKKciUyxN4MsBXIOeiovVbWr8',
    appId: '1:481892702421:web:af69990a230a23538dea5c',
    messagingSenderId: '481892702421',
    projectId: 'graduatoin-project',
    authDomain: 'graduatoin-project.firebaseapp.com',
    storageBucket: 'graduatoin-project.firebasestorage.app',
    measurementId: 'G-Z8WJJVLZQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj77nMik4kHIw4x-7VmuOyysX4Q1VsIH4',
    appId: '1:481892702421:android:7616f16dbeb841cb8dea5c',
    messagingSenderId: '481892702421',
    projectId: 'graduatoin-project',
    storageBucket: 'graduatoin-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-BhBdY-dHHIO15F9Imi1XmDXZHCnSxVg',
    appId: '1:481892702421:ios:7e712d55d80702cf8dea5c',
    messagingSenderId: '481892702421',
    projectId: 'graduatoin-project',
    storageBucket: 'graduatoin-project.firebasestorage.app',
    iosBundleId: 'com.example.managerApp',
  );
}
